/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiaRouteImport } from './routes/sia'
import { Route as MyLearningRouteImport } from './routes/my-learning'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HelpRouteImport } from './routes/help'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResumeJourneyCourseIdRouteImport } from './routes/resume-journey.$courseId'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as VideoSlugPlayerRouteImport } from './routes/$videoSlug.player'
import { Route as PlayerCourseIdVideoIdRouteImport } from './routes/player.$courseId.$videoId'

const SiaRoute = SiaRouteImport.update({
  id: '/sia',
  path: '/sia',
  getParentRoute: () => rootRouteImport,
} as any)
const MyLearningRoute = MyLearningRouteImport.update({
  id: '/my-learning',
  path: '/my-learning',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeJourneyCourseIdRoute = ResumeJourneyCourseIdRouteImport.update({
  id: '/resume-journey/$courseId',
  path: '/resume-journey/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const VideoSlugPlayerRoute = VideoSlugPlayerRouteImport.update({
  id: '/$videoSlug/player',
  path: '/$videoSlug/player',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerCourseIdVideoIdRoute = PlayerCourseIdVideoIdRouteImport.update({
  id: '/player/$courseId/$videoId',
  path: '/player/$courseId/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/events': typeof EventsRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/my-learning': typeof MyLearningRoute
  '/sia': typeof SiaRoute
  '/$videoSlug/player': typeof VideoSlugPlayerRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/resume-journey/$courseId': typeof ResumeJourneyCourseIdRoute
  '/player/$courseId/$videoId': typeof PlayerCourseIdVideoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/events': typeof EventsRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/my-learning': typeof MyLearningRoute
  '/sia': typeof SiaRoute
  '/$videoSlug/player': typeof VideoSlugPlayerRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/resume-journey/$courseId': typeof ResumeJourneyCourseIdRoute
  '/player/$courseId/$videoId': typeof PlayerCourseIdVideoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/events': typeof EventsRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/my-learning': typeof MyLearningRoute
  '/sia': typeof SiaRoute
  '/$videoSlug/player': typeof VideoSlugPlayerRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/resume-journey/$courseId': typeof ResumeJourneyCourseIdRoute
  '/player/$courseId/$videoId': typeof PlayerCourseIdVideoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/checkout'
    | '/contact'
    | '/courses'
    | '/events'
    | '/help'
    | '/login'
    | '/my-learning'
    | '/sia'
    | '/$videoSlug/player'
    | '/blog/$slug'
    | '/resume-journey/$courseId'
    | '/player/$courseId/$videoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/checkout'
    | '/contact'
    | '/courses'
    | '/events'
    | '/help'
    | '/login'
    | '/my-learning'
    | '/sia'
    | '/$videoSlug/player'
    | '/blog/$slug'
    | '/resume-journey/$courseId'
    | '/player/$courseId/$videoId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/checkout'
    | '/contact'
    | '/courses'
    | '/events'
    | '/help'
    | '/login'
    | '/my-learning'
    | '/sia'
    | '/$videoSlug/player'
    | '/blog/$slug'
    | '/resume-journey/$courseId'
    | '/player/$courseId/$videoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  BlogRoute: typeof BlogRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRoute
  EventsRoute: typeof EventsRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  MyLearningRoute: typeof MyLearningRoute
  SiaRoute: typeof SiaRoute
  VideoSlugPlayerRoute: typeof VideoSlugPlayerRoute
  ResumeJourneyCourseIdRoute: typeof ResumeJourneyCourseIdRoute
  PlayerCourseIdVideoIdRoute: typeof PlayerCourseIdVideoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sia': {
      id: '/sia'
      path: '/sia'
      fullPath: '/sia'
      preLoaderRoute: typeof SiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-learning': {
      id: '/my-learning'
      path: '/my-learning'
      fullPath: '/my-learning'
      preLoaderRoute: typeof MyLearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume-journey/$courseId': {
      id: '/resume-journey/$courseId'
      path: '/resume-journey/$courseId'
      fullPath: '/resume-journey/$courseId'
      preLoaderRoute: typeof ResumeJourneyCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/$videoSlug/player': {
      id: '/$videoSlug/player'
      path: '/$videoSlug/player'
      fullPath: '/$videoSlug/player'
      preLoaderRoute: typeof VideoSlugPlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/$courseId/$videoId': {
      id: '/player/$courseId/$videoId'
      path: '/player/$courseId/$videoId'
      fullPath: '/player/$courseId/$videoId'
      preLoaderRoute: typeof PlayerCourseIdVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  BlogRoute: BlogRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRoute,
  EventsRoute: EventsRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  MyLearningRoute: MyLearningRoute,
  SiaRoute: SiaRoute,
  VideoSlugPlayerRoute: VideoSlugPlayerRoute,
  ResumeJourneyCourseIdRoute: ResumeJourneyCourseIdRoute,
  PlayerCourseIdVideoIdRoute: PlayerCourseIdVideoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
